#!/bin/bash
if [[ -n "$LOADER_EZFFF_0A4D2461_LOADED" ]]; then return 0; fi
export LOADER_EZFFF_0A4D2461_LOADED=1
export LOADER_EZFFF_0A4D2461_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

# Core
source "$LOADER_EZFFF_0A4D2461_DIR/fff_functions/fff_compress.sh"
source "$LOADER_EZFFF_0A4D2461_DIR/fff_functions/fff_convert.sh"
source "$LOADER_EZFFF_0A4D2461_DIR/fff_functions/fff_help.sh"
source "$LOADER_EZFFF_0A4D2461_DIR/fff_functions/fff_trim.sh"

# Visuals
source "$LOADER_EZFFF_0A4D2461_DIR/fff_functions/fff_resize.sh"
source "$LOADER_EZFFF_0A4D2461_DIR/fff_functions/fff_rotate.sh"
source "$LOADER_EZFFF_0A4D2461_DIR/fff_functions/fff_flip.sh"
source "$LOADER_EZFFF_0A4D2461_DIR/fff_functions/fff_crop.sh"

# Effects
source "$LOADER_EZFFF_0A4D2461_DIR/fff_functions/fff_speed.sh"
source "$LOADER_EZFFF_0A4D2461_DIR/fff_functions/fff_reverse.sh"
source "$LOADER_EZFFF_0A4D2461_DIR/fff_functions/fff_grayscale.sh"

source "$LOADER_EZFFF_0A4D2461_DIR/fff.sh"

# Tests
source "$LOADER_EZFFF_0A4D2461_DIR/tests/test_fff.sh"
source "$LOADER_EZFFF_0A4D2461_DIR/tests/test_fff_visual.sh"
